### ISSUE TITLE
Prevent re-naming the folder of a site?

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#562]
I've not given this much though or testing, but noticed in passing that if you change the Site Folder Name in Site Settings, you lose anything previously created in the site. 
![image](https://user-images.githubusercontent.com/10574730/52598798-cc371700-2e4e-11e9-9df1-62ff2357ff3f.png)

This surprised me as a) it lets you change it, and b) I assumed things hang together by the site guid.

Is this expected, and if so, would it be wise to prevent changing this in a site already created with content, or at least giving a fierce warning?

**Comment by joeaudette** [comment]
I just fixed an issue with caching. If the site folder name was changed it was not clearing the cache for the old folder so the old folder was still working with the cached copy of site settings. Also the folder list used to resolve folder sites was also cached and needed to be cleared so the new folder would work.

I've just published updated nuget for cloudscribe.Core.Web.

While it may not be a good idea to change the folder of an existing site for seo reasons I don't think we should block admins from doing what they want.

As far as losing anything previously created in the site, I assume you are talking about simplecontent. I would not expect changing the site name to break simplecontent because it is tied together by the site guid. However, links could be broken if the content had links to pages with the old folder.  

Are you sure you really lost content? I suspect it could have been a caching issue that may have resolved itself when the cache expired or was later cleared. The cache issue should now be resolved with the latest nugets. I've just tested changing a site folder after updating to the latest cloudscribe core nuget and it did not break simplecontent and nothing was lost.

**Comment by CrispinF** [comment]
@joeaudette yes the caching issue would explain what I saw. My content was not really lost, I just couldn't get to it!

**Comment by CrispinF** [comment]
@joeaudette just noting that this was possibly not fixed for me.  Running the site from VS, I changed the site folder, and then couldn't access the content. Going to the new folder took me to a "create page" form.   On stopping the site and restarting, the new folder worked fine.   Possibly this was a result of running in from VS? I'll try on the production site, but just wanted to note this.

**Comment by CrispinF** [comment]
Also, I wonder if this has affected the caching of site menu? I've just changed an Override URL and it hasn't taken effect.  On re-starting the site, the override becomes apparent in the menu.

**Comment by joeaudette** [comment]
Well it was fixed, then broken, and now fixed again in latest nugets.

A few days ago I updated the navigation library to use IDistributedCache by default, it actually uses a memory implementation of that so it isn't really distrbuted but then all someone has to do is inject a real implementation of IDistributedCache to make it distributed.

Simple content was naively clearing memory cache not distributed cache. It actually took a good bit of refactoring in simplecontent to solve it. I injected ITreeCache which is a navigation project interface into PageService so I could call its clear cache method. But then I ran into a circular dependency error because the tree cache depends on a list of treebuilders and pagesnavigationtreebuilder is one of those and it depends on pageservice. So I had to factor out all the cache clearing logic of simplecontent to be separate from page service because I can't inject ITreeCache into Page  service without causing the circular dependency error.
