### ISSUE TITLE
Count of users in roles can be incorrect on Role Management screen (nodb - not tested on other platforms)

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#870]
To replicate (in a new site created from template, with noDB storage), log in as admin@admin.com, create another user account, add it to the Administrators role. Log out, and log in with the new user account. Delete the admin@admin.com account.
I suspect the counts will be incorrect now, but actually I then also configured social auth against an Azure AD, and signed in with a different account, thus creating a second user in the site. I then noticed that the role user counts were wrong. But I think this step was irrelevant.
At this point the counts were as follows:
![image](https://user-images.githubusercontent.com/10574730/219941258-15cc99df-ec2f-4c24-aa1a-08bec77f5510.png)

On opening the Administrators role there's only one user, as expected (so the count of 2 is incorrect). On opening the Authenticated Users role there are actually 3 users, again as expected, so the count of 3 is wrong.

**Comment by CrispinF** [comment]
Incidentally, on adding a second user to the Administrators role, the count now rises to 3!

**Comment by JimKerslake** [comment]
This will be a NoDb specific issue I think.
Delete a user >> the entries from UserRole are not deleted.

**Comment by JimKerslake** [comment]
fixed cloudscribe.Core.Storage.NoDb  at 6.0.1

**Comment by CrispinF** [comment]
Tested on a NoDB site. Removing a user from a role decrements the count by one, and adding increments by one.
PASS.
However, and it's a big one, the numbers are still incorrect on my site as adding/subtracting one doesn't give the correct counts.
Why is the count not an actual count? Is this cached in the role table, rather than actually counted, and so forever wrong?
That doesn't feel like a good solution, given how inexpensive an operation this count would be, and how infrequently the roles screen is accessed typically. @JimKerslake I'm happy we've fixed the immediate bug, but should we raise another issue to change this, or are there good reasons to leave as is?

**Comment by JimKerslake** [comment]
You're in NoDb here, and the count **is** an actual count of the json files stashed in the UserRole folder.
Trouble is, if you've had the bug in the past, then deleting a user will have failed to delete that user's role-mapping json files here, leaving some orphans sitting there indefinitely.
Bug now fixed so that in future the 'cascade delete' will happen - but those extra stray orphans will remain unless manually removed.
We could add more code to clean up any orphans in this (and any other) relational folders... kind of mopping up after the effects of historical bugs... but going forward this particular one should cease to be an issue.

**Comment by CrispinF** [comment]
@JimKerslake ok thanks for checking... if this is already a genuine count I'm happy we don't need to do any more. I don't think we should add code to mop up from previous bugs unless it's to resolve serious problems (and this isn't). Closing.

**Comment by JimKerslake** [comment]
Looks like the same thing in the EF databases too...?

**Comment by StewartBellamy** [comment]
@JimKerslake - yes, when a user is deleted it does not remove the row(s) from cs_UserRole.
